use std::error::Error;

pub fn part_two(path: &str) -> Result<usize, Box<dyn Error>> {
    todo!()
}
